[package]
name = "wrkspc-macro"
version = "0.0.0"
authors = ["eupn <eupn@protonmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "1.0"

[dev-dependencies]
macrotest = { path = "../../" }
