[package]
name = "wrkspc-test"
version = "0.0.0"
edition = "2018"

[lib]

[features]
default = []

test-feature = []

[dev-dependencies]
macrotest = { path = "../../" }
inventory = "0.2.2"

[[test]]
name = "workspace-tests"
path = "src/main.rs"
harness = false
