name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install
        if: matrix.os == 'windows-latest'
        run: |
          rustup target add x86_64-pc-windows-msvc

      - name: before script
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt
          cargo install $TARGET cargo-expand

      - name: script
        run: |
          cargo build $TARGET --verbose --all
          cargo test
          cd test-project
          cargo test -- --nocapture
          cd ../test-procmacro-project
          cargo test -- --nocapture


